version: '3.8'
services:
  service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: wallet_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: unless-stopped